# Generated by Django 5.1.3 on 2025-01-07 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieQuiz',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('auteur', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('texte', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id_choix', models.AutoField(primary_key=True, serialize=False)),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id_questionnaire', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('niveau', models.CharField(choices=[('facile', 'Facile'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='facile', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='quiz.categoriequiz')),
                ('niveau_suivant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveau_precedent', to='quiz.questionnaire')),
            ],
            options={
                'unique_together': {('titre', 'categorie', 'niveau')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.questionnaire'),
        ),
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultatQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('facile', 'Facile'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='facile', max_length=50)),
                ('score', models.FloatField()),
                ('score_cat', models.FloatField(default=0)),
                ('termine', models.BooleanField(default=False)),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='quiz.categoriequiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_quiz', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'categorie', 'niveau', 'date_passage')},
            },
        ),
    ]
