# Generated by Django 5.1.3 on 2025-01-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choix',
            name='est_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='questionnaire',
            unique_together={('titre', 'categorie')},
        ),
    ]
