# Generated by Django 5.1.3 on 2025-01-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_choix_est_correct_alter_questionnaire_titre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriequiz',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
